version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: irrigo_postgres
    restart: always
    environment:
      POSTGRES_USER: irrigo_user
      POSTGRES_PASSWORD: irrigo_password
      POSTGRES_DB: irrigo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: irrigo_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@irrigo.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
